### ISSUE TITLE
Add an example with rendering to a GLFW window

### ISSUE THREAD

**Issue by eterevsky** [kyamagu/skia-python#105]
skia-python tutorial contains an example of [rendering to a headless OpenGL context](https://kyamagu.github.io/skia-python/tutorial/canvas.html#gpu). I tried to modify the example to render to the actual window on the screen, but ended up with a black window:

```python
import glfw
import skia

width, height = 640, 480

def main():
    if not glfw.init():
        return
    glfw.window_hint(glfw.STENCIL_BITS, 8)
    window = glfw.create_window(width, height, "Hello World", None, None)
    if not window:
        glfw.terminate()
        return

    glfw.make_context_current(window)

    context = skia.GrContext.MakeGL()
    info = skia.ImageInfo.MakeN32Premul(width, height)
    surface = skia.Surface.MakeRenderTarget(context, skia.Budgeted.kNo, info)
    assert surface is not None

    while not glfw.window_should_close(window):
        with surface as canvas:
            canvas.drawCircle(100, 100, 40, skia.Paint(Color=skia.ColorGREEN))
        surface.flushAndSubmit()

        glfw.swap_buffers(window)
        glfw.poll_events()

    context.abandonContext()
    glfw.terminate()

if __name__ == "__main__":
    main()
```

I don't understand why it doesn't work. It would be nice to add to the documentation at least on example of rendering to a live window.

**Comment by kyamagu** [comment]
See this https://github.com/kyamagu/skia-python/issues/97#issuecomment-652840290

Yes, adding an example would be nice

**Comment by eterevsky** [comment]
Thank you! This works correctly. I created a PR adding similar example to the Tutorial.
