### ISSUE TITLE
AttributeError: type object 'skia.GrContext' has no attribute 'MakeGL'

### ISSUE THREAD

**Issue by FlorianLudwig** [kyamagu/skia-python#110]
**Describe the bug**
Example in docs raises exception

**To Reproduce**
1. `pip install skia-python==86.0 glfw==1.12.0`
2. run example from tutorial: https://kyamagu.github.io/skia-python/tutorial/canvas.html#gpu
3. Get error:
```
AttributeError: type object 'skia.GrContext' has no attribute 'MakeGL'
```

**Expected behavior**
Working example in documentation

**Desktop (please complete the following information):**
 - OS: Linux
 - Python: 3.8
 - skia-python version: 86.0

**Comment by kyamagu** [comment]
Thanks, fixed

**Comment by FlorianLudwig** [comment]
@kyamagu hey, thanks for the quick reply.

With the new version I don't get a surface and line 30:
```
    assert surface is not None
```

Results in an `AssertionError`. Any idea why?

**Comment by kyamagu** [comment]
Can you check if the older skia version with the use of `GrContext` works?

```bash
pip install skia-python==85.0
```

**Comment by FlorianLudwig** [comment]
Same error, `surface = None`.

**Comment by kyamagu** [comment]
Ok, that could be a driver issue. Make sure you have system requirement. Might also need `xvfb`.

https://kyamagu.github.io/skia-python/install.html#pypi-distribution

**Comment by FlorianLudwig** [comment]
I usually use wayland and tried running it on xorg instead - that worked. I will investigate further how to make that work. Is there a way to get skia / skia python to be more verbose about issues/errors?

**Comment by kyamagu** [comment]
Skia-python is merely a thin wrapper around Skia library, and perhaps you need to check [the skia source code](https://skia.googlesource.com/skia).

The error is likely happening around OpenGL context creation, and you might need to instead check if `glfw` or whatever toolkit can correctly reveal OpenGL for skia in your environment.
