### ISSUE TITLE
Set a render region rectangle, only draw inside it

### ISSUE THREAD

**Issue by Tremeschin** [kyamagu/skia-python#111]
**Is your feature request related to a problem? Please describe.**

I'm attempting to write a basic and GUI "toolkit" using `skia-python` as I find it hard Qt and GTK programming and liked too much Skia's general flexibility, but for making "widgets" like a file explorer or a combo box or input text it's no good to show everything at once (the items on a list), we need to limit the render "target region".

**Describe the solution you'd like**

I tried finding documentation on it and couldn't, sorry if it's there and exists, I wanted to do something like:

- `canvas.draw(what, x, y, paint, REGION)`

This regions limits on where Skia will stop writing to the canvas window, let's saw I write a text of size `(w=200, h=20)` at coordinate `(x=0, y=0)` and specify a region of: 

- `REGION = (Xstart=0, Ystart=0, Xend=100, Yend=20)`

So in this case it'll only render half the text, more specifically the first half of it and won't render the outside parts of this rectangle.

**Describe alternatives you've considered**

I could draw into a new canvas and then merge the two but that'd make things spaghetti and I'm not sure how OpenGL would behave, I considered hard drawing the outside of the region with black rectangles but that will overwrite the other parts of the GUI.

**Additional context**

Thanks for this binding / package, it saved me a lot of SVG pain I had and is really fast under Python.

**Comment by kyamagu** [comment]
I believe you can use Canvas clipping APIs (e.g., [`clipRect`](https://kyamagu.github.io/skia-python/reference/skia.Canvas.html#skia.Canvas.clipRect))

**Comment by Tremeschin** [comment]
Thanks a lot!! This worked exactly the way I expected. As simple as:

- `canvas.clipRect(skia.Rect(box_x, box_y, box_w, box_h))`

And then drawing the items afterwards, then resetting the clip rect to the full resolution itself to draw the other components.
