### ISSUE TITLE
Not able to pip install skia-python

### ISSUE THREAD

**Issue by AjayrajSingh** [kyamagu/skia-python#119]
I don't know if its package a sided issue, python sided or env sided. But every time I'm pip installing skia-python its given me this error:
ERROR: Could not find a version that satisfies the requirement skia-python==86.0 (from versions: none)
ERROR: No matching distribution found for skia-python==86.0

**Comment by AjayrajSingh** [comment]
It seems to be in python 3.8 and above, I installed python 3.6 and it began working fine.

**Comment by kyamagu** [comment]
Hard to tell the cause without specific platform info, but likely outdated pip version issue

**Comment by AjayrajSingh** [comment]
So I basically solved this by degrading my python version to python 3.6. Seems this plugin doesn't support python 3.8 and above.
