### ISSUE TITLE
Unable to install on macOS Big Sur

### ISSUE THREAD

**Issue by splatte** [kyamagu/skia-python#132]
**Describe the bug**
I am unable to install skia-python using pip on macOS Big Sur 11.0.1, error: "Could not find a version that satisfies the requirement skia-python".

**To Reproduce**
Setting up a new project using venv, updating pip, then installing skia-python:

```
/tmp ➤ python3 -m venv skia-bigsur
/tmp ➤ cd skia-bigsur
skia-bigsur ➤ source bin/activate
(skia-bigsur) skia-bigsur ➤ python -m pip install --upgrade pip
...
(skia-bigsur) skia-bigsur ➤ python -m pip install skia-python
ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none)
ERROR: No matching distribution found for skia-python
```

However, when I download and rename the wheel file from pypi, it seems to be able to install it just fine and lets me import:

```
(skia-bigsur) skia-bigsur ➤ wget https://files.pythonhosted.org/packages/a1/17/4973bc6ae96e418f4ff8c1cc664d95d33714017bd70e7dee460587b18ab6/skia_python-87.0-cp39-cp39-macosx_10_14_x86_64.whl
(skia-bigsur) skia-bigsur ➤ mv skia_python-87.0-cp39-cp39-macosx_10_14_x86_64.whl skia_python-87.0-cp39-cp39-macosx_11_0_x86_64.whl
(skia-bigsur) skia-bigsur ➤ python -m pip install skia_python-87.0-cp39-cp39-macosx_11_0_x86_64.whl
...
(skia-bigsur) skia-bigsur ➤ python
Python 3.9.0 (default, Nov 21 2020, 14:55:42)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import skia
>>>
```

**Expected behavior**
skia-python should install successfully 

**Desktop (please complete the following information):**
 - OS: macOS 11.0.1 Big Sur
 - Python: 3.9.0
 - skia-python version: 87.0

**Additional context**
-

**Comment by kyamagu** [comment]
Likely pip issue https://github.com/pypa/pip/issues/9138

**Comment by splatte** [comment]
@kyamagu thanks to your pointer I was able to follow the release of pip 20.3 which has just happened. sure enough, after upgrading the installation works successfully now. I'll close this issue.
