### ISSUE TITLE
Important Paint.textAlign property is not implemented

### ISSUE THREAD

**Issue by tushar5526** [kyamagu/skia-python#135]
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skpaint.textalign?view=skiasharp-1.68.2
There are no bindings to the `paint.textAlign` property in `Paint` class, can you add it?

**Comment by kyamagu** [comment]
There isn't textAlign API in Skia. Maybe specific extension to skia sharp?
https://api.skia.org/classSkPaint.html

**Comment by tushar5526** [comment]
Yes, it seems it is specific to skia sharp. I think I have to handle text alignment myself.
Thanks !
