### ISSUE TITLE
skia.Typeface.MakeFromFile() (ttc)index argument not working

### ISSUE THREAD

**Issue by justvanrossum** [kyamagu/skia-python#138]
**Describe the bug**
The optional `index` argument of `skia.Typeface.MakeFromFile(path, index=0)` is supposed to be the index to a font in a .ttc (TT collection) file, but this does not work.

**To Reproduce**
1. Use the attached testfont "MutatorSans.ttc" (or any .ttc containing more than one font)
2. Run:
```python
>>> import skia
>>> p = "/Users/just/code/git/fontgoggles/Tests/data/MutatorSans/MutatorSans.ttc"
>>> skia.Typeface.MakeFromFile(p, 0)
Typeface('MutatorMathTest', FontStyle(400, 5, Slant.kUpright_Slant))
>>> skia.Typeface.MakeFromFile(p, 1)
>>> 
```

**Expected behavior**
The second call to `skia.Typeface.MakeFromFile()` should also return a Typeface, but it returns None.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.15.7]
 - Python: [e.g. 3.9.0]
 - skia-python version: [e.g., v87.1]

**Additional context**
Here is a .ttc file to test with (but any .ttc should show the problem)
[MutatorSans.ttc.zip](https://github.com/kyamagu/skia-python/files/6180976/MutatorSans.ttc.zip)

**Comment by justvanrossum** [comment]
Oh, I just ran this on GH Actions on Linux and Win and macOS: the problem only exists on macOS.

**Comment by HinTak** [comment]
Since it is just a direct call to a single upstream routine: https://github.com/kyamagu/skia-python/blob/f71fdeeeea6eeb0785f045109871c24b2ee1ec01/src/skia/Font.cpp#L575 , I think it is an upstream bug and you should report it upward. FWIW, I put a test through GH action with m117 and it is still failing, on mac os x, and only on mac os x. So you should file upstream against m117 / current.

**Comment by HinTak** [comment]
Just a heads-up: this API is being deprecated upstream in skia https://github.com/google/skia/blob/main/relnotes/typeface.md - so we'll have to either emulate it in skia-python for backward-compatibility, or just drop it, in m120+ . 

Either way, you might consider using the FontMgr API as it says... I had an impression that there is no platform-specific APIs in skia-python (except the one I added a couple of months ago on COLRv1 fonts on freetype-based platforms), so it probably does not exist in skia-python yet. So here is a chance for you to influence how FontMgr_mac_ct should work in skia-python, for it to be added.

**Comment by HinTak** [comment]
Filed upstream https://issues.skia.org/issues/310510989

**Comment by HinTak** [comment]
See also https://github.com/kyamagu/skia-python/issues/213 - that might workaround this issue when it lands. The tests already include a variant of this test set.

**Comment by HinTak** [comment]
I think `skia.Typeface.MakeFromFile(p, N)` is equivalent to invoking the default system font manager (CoreText) like this:
`skia.FontMgr().makeFromFile(p, N)` which does not work against CoreText. This is filed upstream 
https://issues.skia.org/issues/310510989.

However, while looking for something else, I came across some info that Chrome on all platforms can use FreeType for font formats which the host font manager does not support - this include CBDT color fonts on Apple, variation fonts on old versions of windows, and etc. This is invoked via 
`skia.FontMgr.New_Custom_Empty()` to get a "custom (ie based on feeetype and non-host) Empty (have no access to system platform built-in fonts)" font manager, and load your font via this custom empty font manager: 
`skia.FontMgr.New_Custom_Empty().makeFromFile(p, N)` .

And I have tested this in my playground pull https://github.com/HinTak/skia-m1xx-python/pull/6 , and tidy up in #210 .

So if you really want it to work with the default CoreText based font manger, bug Google folks at the upstream URL; if you just like it to work "somehow" on mac OS, when m120 #210 get merged you can do load via freetype on mac os with:
`skia.FontMgr.New_Custom_Empty().makeFromFile(p, N)` .

Of course I would like CoreText to work... close for now.
