### ISSUE TITLE
PyPi wheel name scheme changed

### ISSUE THREAD

**Issue by alerque** [kyamagu/skia-python#140]
I'll preface this by saying Python Wheel naming schemes are bizarrely complex to my eye anyway so their *may* be a reason for this. However the new scheme includes even more duplicate or nonsense information that the last one:

* Old: `skia_python-87.1-cp39-cp39-manylinux2014_x86_64.whl`
* New: `skia_python-87.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`

Is the extra `manylinux_2_17_86_64.` actually serving a purpose? It's bad enough that `cp39` is duplicated...

As a distro packager every time something like this changes we have to go futz around and figure out what the new scheme is. It would be nice if it made more sense and didn't change between releases without good cause.

**Comment by kyamagu** [comment]
The new scheme includes explicit glibc version, and they are automatically labeled via [`auditwheel`](https://github.com/pypa/auditwheel) in skia-python.

**Comment by alerque** [comment]
Bah humbug is what I say. This is debug info that could have gone *inside* the package instead of on the label. Since only one alternative is offered and it does not need to match the glibc on the host system to run it is irrelevant detail about the build system that packagers have to know and update periodically for no gain in end users being able to pick the right package.

If you don't plan on fixing this by turning off whatever option is relevant, just close this issue. Just color your distro packagers somewhat annoyed.
