### ISSUE TITLE
Skia Shaders

### ISSUE THREAD

**Issue by awesome-developer-20** [kyamagu/skia-python#141]
Does skia-python support [sksl](https://skia.org/docs/user/sksl/) (Skia’s shading language)?

**Comment by kyamagu** [comment]
Not yet

**Comment by awesome-developer-20** [comment]
Do you have any plans for supporting sksl in skia-python?

**Comment by kyamagu** [comment]
@awesome-developer-20 No plan as of now, but welcome PRs

**Comment by HinTak** [comment]
@awesome-developer-20 it does when this pull https://github.com/kyamagu/skia-python/pull/274 get merged, which is basically in the next few days, when I put m132 into it too. Close this when #274 is merged.

**Comment by HinTak** [comment]
#274 merged. M132 will be tagged and out tomorrow.
