### ISSUE TITLE
Init a scene by a function?

### ISSUE THREAD

**Issue by ReneTC** [kyamagu/skia-python#142]
I am trying to use this brilliant package to make some functions/classes easier to use this package. I have one major issue and after reading the docs I can't seem to find the right solution. I'm looking to make a function that generates a scene to write to.. Something like this:
```

import skia
from IPython.display import display, Image

def init_scene(x,y):
    surface = skia.Surface(x, y)
    with surface as canvas:
        canvas.clear(skia.ColorWHITE)

def draw_cube_to_scene():
    rect = skia.Rect.MakeXYWH(-90.5, -90.5, 181.0, 181.0)
    paint = skia.Paint()
    paint.setColor(skia.ColorBLUE)
    canvas.drawRect(rect, paint)
    canvas.restore()
    image = surface.makeImageSnapshot()
    display(Image(data=image.encodeToData()))

init_scene(500,200)
draw_cube_to_scene()
```
results in: ERROR name 'canvas' is not defined

For the example to work the surface and canvas cannot be locally in a function/class. So this works:

```
import skia
from IPython.display import display, Image

surface = skia.Surface(500, 200)
with surface as canvas:
    canvas.clear(skia.ColorWHITE)

def draw_cube_to_scene():
    rect = skia.Rect.MakeXYWH(-90.5, -90.5, 181.0, 181.0)
    paint = skia.Paint()
    paint.setColor(skia.ColorBLUE)
    canvas.drawRect(rect, paint)
    canvas.restore()
    image = surface.makeImageSnapshot()
    display(Image(data=image.encodeToData()))

draw_cube_to_scene()
```
Results in a nice cube
![image](https://user-images.githubusercontent.com/40211569/123263502-500e6d00-d4f9-11eb-89dc-732dc9a7c578.png)

But now the user cannot create a new scene with custom size of graphics. Do you know it is possible to do the first example? I would love your help.

**Comment by kyamagu** [comment]
You can use `contextlib.contextmanager` instead of function + global variable

**Comment by ReneTC** [comment]
Thanks for getting back to me @kyamagu !
I see in the examples you have used it. But I cannot get it to work .. I did it but was only able to draw one box..
Here is my attempt so far, do you  mind helping some more? 

```
import skia
from IPython.display import display, Image
import contextlib

@contextlib.contextmanager
def init_scene(x,y):
    surface = skia.Surface(x, y)
    with surface as canvas:
        yield canvas

def draw_cube_to_scene(x,y):
    rect = skia.Rect.MakeXYWH(x, y, 181.0, 181.0)
    paint = skia.Paint()
    paint.setColor(skia.ColorBLUE)
    canvas.drawRect(rect, paint)
    canvas.restore()

init_scene(500,200)

# draw two cubes
draw_cube_to_scene(100,100)
draw_cube_to_scene(0,300)

# after drawing, show image
image = surface.makeImageSnapshot()
display(Image(data=image.encodeToData()))

```
Results in: name 'canvas' is not defined

**Comment by kyamagu** [comment]
well, you have to scope everything under `with` statement

```python
with init_scene(500,200) as canvas:
    # do whatever here with the canvas
```

You must explicitly manage surface / canvas. If you need to exclude them in the function args, make them a global variable. Those instances must not go out of scope.

**Comment by ReneTC** [comment]
Dear @kyamagu  thaks for taking the time to explain this to me. Because I am very interested in keeping the original format I made some wacked code with "exec" to avoid using scoping everything under the with statement as you suggest. I'm posting it here if anyone is interested but I know the code is bad
```

import skia
from IPython.display import display, Image
import contextlib

def init_scene(x,y):
    code = '''width, height = '''+str(x)+''',  '''+str(y)+'''
surface = skia.Surface(width, height)
with surface as canvas:
    canvas.clear(skia.ColorWHITE)
    '''
    exec(code, globals())


def draw_cube_to_scene(x,y):
    rect = skia.Rect.MakeXYWH(x, y, 181.0, 181.0)
    paint = skia.Paint()
    paint.setColor(skia.ColorBLUE)
    canvas.drawRect(rect, paint)
    canvas.restore()

init_scene(500,200)
draw_cube_to_scene(100,100)
draw_cube_to_scene(0,300)

# after drawing, show image
image = surface.makeImageSnapshot()
display(Image(data=image.encodeToData()))
```
