### ISSUE TITLE
Can you provide a custom ttf font for skia font?

### ISSUE THREAD

**Issue by ReneTC** [kyamagu/skia-python#143]
I'm trying to use a custom font. I know you can specify with some string like skia.Typeface("Arial").
However, can you also give a custom path to a font file somehow?

**Comment by kyamagu** [comment]
See [`skia.Typeface.MakeFromFile`](https://kyamagu.github.io/skia-python/reference/skia.Typeface.html#skia.Typeface.MakeFromFile)

**Comment by ReneTC** [comment]
works like a charm.. thank you!
