### ISSUE TITLE
Loading an image as paint

### ISSUE THREAD

**Issue by ReneTC** [kyamagu/skia-python#144]
Is it possible to draw an image on a "canvas.drawRect" object?

I know you can do 

```
paint = skia.Paint(
    AntiAlias=True,
    Color=color,
    Style=skia.Paint.kFill_Style,
    )
canvas.drawRect(skia.Rect.MakeXYWH(x,y, width, height), paint)
```
Is there a commad in paint that allwos to load an image and display it on a rectangle?

**Comment by kyamagu** [comment]
I believe you can apply [`ImageFilters`](https://kyamagu.github.io/skia-python/reference/skia.ImageFilters.html#skia.ImageFilters)

**Comment by ReneTC** [comment]
Thank you. I haven't got it to work yet but I tried making the new paint object to apply to a skia.rect;
```
    image = skia.Image.open('image/path/image.png')
    paint = skia.Paint(
    AntiAlias=True,
    ImageFilter=image,
    )
```
This does not work and results in the error `RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)`

**Comment by ReneTC** [comment]
Thanks for the help!
I found an example of this here;
https://kyamagu.github.io/skia-python/tutorial/overview.html#more-drawings
