### ISSUE TITLE
canvas.drawTextBlob() not working sometimes with TTF fonts

### ISSUE THREAD

**Issue by RugnarLodbrok** [kyamagu/skia-python#148]
**Describe the bug**
canvas.drawTextBlob() sometimes doesn't draw anything when using ttf fonts

**To Reproduce**
```
import os
import zipfile

import numpy as np
import requests
import skia
from PIL import Image


def get_font_file():
    directory = 'fonts'
    font_file = 'SourceSerifPro-Regular.ttf'
    path = os.path.join(directory, font_file)
    if not os.path.exists(path):
        url = 'https://fonts.google.com/download?family=Source%20Serif%20Pro'
        r = requests.get(url)
        zip_file_name = 'fonts.zip'
        with open(zip_file_name, 'wb') as f:
            f.write(r.content)

        with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
            zip_ref.extractall(directory)
    return path


def get_font(is_custom=False):
    if not is_custom:
        return skia.Font(None, 36)
    else:
        file = get_font_file()
        with open(file, 'rb') as f:
            typeface = skia.Typeface.MakeFromData(f.read())
        return skia.Font(typeface, size=36, scaleX=1.0, skewX=0.0)


def main(is_custom=False, decrement_size=False):
    paint = skia.Paint(
        AntiAlias=True,
        Color=skia.Color(255, 0, 0, 255),
        Style=skia.Paint.kFill_Style,
    )

    font = get_font(is_custom)
    blob = skia.TextBlob('Simple text 123', font=font)

    w, h = 539, 113
    if decrement_size:
        h -= 1
    xy = 10, 50
    frame = np.ones((h, w, 4), dtype=np.uint8) * 255
    with skia.Surface(frame) as canvas:
        canvas.drawTextBlob(blob, *xy, paint)
    Image.fromarray(frame).save('skia!.png')



if __name__ == '__main__':
    # main(False, False)  # works
    # main(False, True)  # works
    # main(True, False)  # works
    main(True, True)  # doesnt't work!
```

**Expected behavior**
Text should be rendered

**Desktop (please complete the following information):**
 - OS: Docker ubuntu:18.04
 - Python: 3.9.6
 - skia-python version: 87.2

**Comment by HinTak** [comment]
@kyamagu Can you have a lookk at the TextBlob class and see if it has a problem of losing reference to the font argument, or it needing to clone/copy the font argument? I am seeing very curious behavior - with m121 and finding the old font, I can see an image of the text, but with the new font, it segfaults at the line `skia.TextBlob('Simple text 123', font=font)`. with the new font and m120, as I wrote above, I got a bound box but not drawing anything (at least in the visible area). So it looks like there is a possibility of that code losing the font - causing segfault in 121, and getting bound box but not drawing in 120. The TextBlob class hasn't changed at all. or some more `py::keep_alive`?

**Comment by kyamagu** [comment]
I suspect the following part. The Python `bytes` as a result of `f.read()` may not be referenced outside the block. Can you check if using `skia.Typeface. MakeFromFile` makes a difference.

```
        with open(file, 'rb') as f:
            typeface = skia.Typeface.MakeFromData(f.read())
```

**Comment by HinTak** [comment]
@kyamagu Thanks. That's it. It must be some kind of lazy evaluation/read - some of typeface is valid, until it is used at the glyph level, then either not drawing or segfault. It is reading the font names, then the rest of the bytes go out of scope.

Here is what it would appear if you have `print(font.getTypeface(), font.getSize())` and `print(blob.bounds())` before and after the `skia.TextBlob` line, plus the one-liner suggested fix from @kyamagu  (just do`typeface = skia.Typeface.MakeFromFile(file)` instead of the two lines)):

```
Typeface('Source Serif 4', FontStyle(400, 5, Slant.kUpright_Slant)) 36.0
Rect(-8.46, -35.928, 320.712, 11.808)

Typeface('Source Serif Pro', FontStyle(400, 5, Slant.kUpright_Slant)) 36.0
Rect(-8.64, -36.072, 310.46, 12.06)
```

**Comment by HinTak** [comment]
Plus already discussed in #222 , upstream no longer supports a "default font", so you shouldn't be using `skia.Font(None, 36)`.
