### ISSUE TITLE
TextBlob.MakeFromPosText not working as expected

### ISSUE THREAD

**Issue by Ocipa** [kyamagu/skia-python#153]
**Describe the bug**
When creating a texblob with a method that takes the text and positions (eg. MakeFromPosText, MakeFromPosTextH and MakeFromRSXform), and the text is a language like Chinese that is 3 bytes per character, it will throw a value error `RuntimeError: text and pos must have the same number of elements.`

**To Reproduce**
tested in vscode notebook

```python
import skia

font = skia.Font()

positions = [(0, 0)]
blob = skia.TextBlob.MakeFromPosText('种', positions, font)
```

will throw `RuntimeError: text and pos must have the same number of elements.` 

**Expected behavior**
is to not error like

```python
blob = skia.TextBlob.MakeFromPosText('a', positions, font)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 19043
 - Python: 3.7.7 in vscode notebook
 - skia-python version: skia.\_\_version\_\_ returns 87.3

**Additional context**
```c++
#include <iostream>
#include <string>

int main()
{
    const std::string& en = "a";
    std::cout << en.size() << std::endl; // prints 1
    
    const std::string& zh = "种";
    std::cout << zh.size() << std::endl; // prints 3
}
```

MakeFromPosText checks if size of text is equal to size of positions, but since it is only 1 character, positions has a size of 1, but the 种 has a size of 3.

**Possible solutions for reference**

- http://www.zedwood.com/article/cpp-utf8-strlen-function

- https://www.cplusplus.com/forum/beginner/192031/

**Comment by HinTak** [comment]
Fixed in https://github.com/kyamagu/skia-python/commit/b79ef6a10844806bdb7df0a75f29b040ca3a1e89 . Build from source or wait for 117b3.

```
>>> import skia # type: ignore
>>> positions = [(0, 150), (140, 150), (280, 150)]
>>> txt = '你好！'
>>> tf = skia.Typeface.MakeFromFile("/usr/share/fonts/adobe-source-han-sans-tw/SourceHanSansTW-Normal.otf")
>>> font = skia.Font(tf, 100)
>>> blob = skia.TextBlob.MakeFromPosText(txt, positions, font)
>>> blob.bounds()
Rect(-100, -30.8, 572.8, 254.8)
>>> 

```
