### ISSUE TITLE
pip install skia-python fails on py3.10, works fine on py3.9

### ISSUE THREAD

**Issue by evtn** [kyamagu/skia-python#160]
**Describe the bug**
skia-python can't be installed using python 3.10 and pip

**To Reproduce**
1. Install Python 3.10
2. `python -m pip install skia-python`

**Expected behavior**
skia-python is installed

**Actual behavior**
`ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none)`

**Desktop (please complete the following information):**
 - OS: Windows 11 21H2
 - Python: 3.10.0
 - skia-python version: n/a

**Additional context**
In the same environment (hardware and OS) installation with pip on python 3.9 works fine.
I believe the issue is that 3.10 is not in the list of supported versions (although I couldn't find the list itself).

**Comment by tjf801** [comment]
I'm running into this issue as well. I see this issue was closed though so am I doing something wrong?

**Comment by kyamagu** [comment]
Fixed in the main branch, but not released yet and not available on PyPI.
[Check artifacts on CI](https://github.com/kyamagu/skia-python/actions/runs/1514648195)
