### ISSUE TITLE
ERROR: No matching distribution found for skia-python==87.4 when building docker with Apple M1

### ISSUE THREAD

**Issue by Adir207** [kyamagu/skia-python#173]
**Describe the bug**
As described in the title, when building docker image on Apple M1, I get the error above.
I'm using python:3.10.2 image, but got the same error with ubuntu:18.04 image

**To Reproduce**
1. Run docker build and try installing skia-python

**Expected behavior**
Build success

**Desktop (please complete the following information):**
 - OS: macOS 12.2
 - Python: 3.10.2
 - skia-python version: v87.4

**Additional context**
I tried:
apt-get install libfontconfig1 libgl1-mesa-glx libgl1-mesa-dri
but it did not help.

Thank you! :)

**Comment by kyamagu** [comment]
Are you building `aarch64` linux image? The current release do not support `aarch64` due to CI issue. The workaround is to use `x86_64` linux image, or manually build the wheel in the target environment.

**Comment by Adir207** [comment]
Thank you for your response!
Is there any estimation for a release that support aarch64? I tried using the workaround Docker official documentation suggested which is adding a --platform linux/amd64 flag on my docker-compose file but it makes the container very slow.
Do you have any reference for manually build the skia-python wheel?
And again, thanks!

**Comment by kyamagu** [comment]
The CI build setup is [here](https://github.com/kyamagu/skia-python/blob/main/.github/workflows/ci.yml), which internally calls the [linux build script](https://github.com/kyamagu/skia-python/blob/main/scripts/build_Linux.sh).

The Github Actions runners do not support a native aarch64 environment, and qemu aarch64 on a x86_64 runner easily timeouts to build. It is unlikely the situation changes anytime soon.

**Comment by Adir207** [comment]
Thanks, I still hope that there will be a release in the near future that will support aarch64 😃

**Comment by Adir207** [comment]
Hi,
I noticed that Github added support for M1 aarch64 actions runners:
[https://github.com/actions/runner/blob/main/releaseNote.md](url)
Any chance you to try adding the build for aarch64? It would be amazing!
Thanks :)

**Comment by kyamagu** [comment]
I do not have any plan to use *self-hosted runners*, but only [*github-hosted runners*](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners). Hope Github offers those.

**Comment by Adir207** [comment]
So, since Github added such a support for only future implementation (not even for this year), I am trying to manually build the wheel in my Docker based on python 3.10 image.
This are the steps I'm currently doing (according to the official build instructions):

RUN git clone --recurse-submodules https://github.com/kyamagu/skia-python.git
WORKDIR /skia-python
ENV PATH="$PWD/depot_tools:$PATH"
RUN git clone https://gn.googlesource.com/gn
WORKDIR /skia-python/gn
ENV CC=gcc
ENV CXX=g++
ENV AR=ar
ENV CFLAGS="-Wno-deprecated-copy"
ENV LDFLAGS="-lrt"
RUN git checkout 981f46c64d1456d2083b1a2fa1367e753e0cdc1b
RUN python ./build/gen.py
RUN ninja -C out gn
WORKDIR /
WORKDIR /skia-python/skia
RUN python tools/git-sync-deps
RUN ../gn/out/gn gen out/Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false extra_cflags_cc=["-frtti"]'
RUN ninja -C out/Release skia skia.h

The last line failed running with the following error:
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

I googled the issue and the suggestion is to use a --platform flag, which is exactly what I'm trying to avoid.
Do you have any suggestion on what could help? I'll be more than happy to share a working shell script once I'm done so users with Apple silicon will be able to use it 😄
