### ISSUE TITLE
SkSVGDOM::renderNode() is not exposed in python

### ISSUE THREAD

**Issue by HinTak** [kyamagu/skia-python#192]
**Is your feature request related to a problem? Please describe.**

According to:
https://github.com/kyamagu/skia-python/blob/main/src/skia/SVGDOM.cpp

SkSVGDOM::RenderNode() is not exposed. It is also not mentioned in the doc.

Look like it shouldn't be too hard?

https://api.skia.org/classSkSVGDOM.html#a28b33bb4471777ee37034f9f8c4766c6

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Looking for skia equivalent of rsvg's render_layer() routine. For OT-SVG support.

**Comment by kyamagu** [comment]
We welcome a PR. Could be that the old m87 branch has different APIs.

**Comment by HinTak** [comment]
It takes an argument of the sort returned by "findNodeByID()", so I am wondering why that entry us commented out in current code? Hmm, oh, that returns a SkSVGSVG type which is not a class in python-skia... But RenderNode() just take a str argument.

Okay, I'll see if I can find my way around...

**Comment by HinTak** [comment]
Skia m88 is the first build where SVG functionality is considered non-experimental (headers moved).

Skia m103 is the first Skia build which contains 9cbadcd9280dc139af2f4d41d25a6c9a750e0302.
That introduces "SkSVGDOM::renderNode()" among other stuff, necessary for rendering "some" OT-SVG fonts. Guess what, that commit is titled "Add optional OT-SVG support to FreeType"! No kidding. :-).

I guess somebody needs to update the skia submodule first. Then we can fix the small m88 breakage (just headers moved), before attempting this.
