### ISSUE TITLE
TextBlob error when I want to control the horizontal spacing of fonts

### ISSUE THREAD

**Issue by haoxurt** [kyamagu/skia-python#200]
I want to control the horizontal spacing of fonts , and I do not find corresponding control parameters. I find TextBlob that can input position list , however，it occurs error when I test with Chinese characters.
blob = skia.TextBlob("一二", font, [(0, 0), (40.5, 0)])
ValueError: len(text) = 6 does not match len(pos) = 2
What should I do? Looking forward to your reply！

**Comment by HinTak** [comment]
You need to count characters (2), not bytes (6). Also, this kind of question is not related to skia-python. Use stackoverflow or just search on Google

**Comment by kyamagu** [comment]
Right, this could be a bug in skia-python. The following size check does not correctly consider character encoding for non-ascii characters.

https://github.com/kyamagu/skia-python/blob/f71fdeeeea6eeb0785f045109871c24b2ee1ec01/src/skia/TextBlob.cpp#L84

**Comment by HinTak** [comment]
Hmm, *every* len check in that file is wrong. It is not friendly, but skia returns null when it fails so there is really no need for the check before passing to skia.

**Comment by HinTak** [comment]
There is another one of the same. https://github.com/kyamagu/skia-python/issues/153

**Comment by HinTak** [comment]
Skia itself counts and valid input https://github.com/google/skia/blob/cc4f9b3469b92c6fcf87a5f151f9441da6652086/src/core/SkTextBlob.cpp#L793 and returns null if the input cannot be parsed. Why are checks scattered all over the place? It is just unnecessary code...

**Comment by HinTak** [comment]
Fixed in https://github.com/kyamagu/skia-python/pull/197/commits/b79ef6a10844806bdb7df0a75f29b040ca3a1e89 . Build from source or wait for 117b3.

```
>>> import skia
>>> tf = skia.Typeface.MakeFromFile("/usr/share/fonts/adobe-source-han-sans-tw/SourceHanSansTW-Normal.otf")
>>> font = skia.Font(tf, 100)
>>> blob = skia.TextBlob("一二", font, [(0, 0), (40.5, 0)])
>>> bounds = blob.bounds()
>>> bounds
Rect(-100, -180.8, 333.3, 104.8)
```

**Comment by kyamagu** [comment]
@HinTak Thanks!
