### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by denis-rochette** [kyamagu/skia-python#206]
Is there any intended support for Python 3.12?

**Comment by HinTak** [comment]
Already done . See https://github.com/kyamagu/skia-python/pull/203 - next (beta) release, probably v119b3 or b4.

**Comment by HinTak** [comment]
Oh, I was going to close this when we push 119bX out - the plan is mostly to get skia-python N out when skia N+1 is available upstream, so we might add a few more things and fix a few more things before m120. If you like, you can monitor when #205 is merged - the merge of that (maybe with another few little changes in the coming weeks) will trigger a new 119 beta release. Skia has a 4-6 week release cycle so m120 is expected in a few weeks.
