### ISSUE TITLE
GL example in tutorial will break on m118+ upgrade

### ISSUE THREAD

**Issue by HinTak** [kyamagu/skia-python#209]
See 
https://github.com/kyamagu/skia-python/pull/204#issuecomment-1786251834

Basically we need to fix (or remove...) the tutorial example before merging m118/m119 (#204 #205 ).

**Comment by HinTak** [comment]
Okay, have a fix. Will put that in #205

**Comment by kyamagu** [comment]
Thanks!

**Comment by HinTak** [comment]
Fixed https://github.com/kyamagu/skia-python/pull/205/commits/c77272c67b094f44779bf62e1d17b4365bff99c8
