### ISSUE TITLE
How to underline and strikethrough fonts？

### ISSUE THREAD

**Issue by haoxurt** [kyamagu/skia-python#224]
How to underline and strikethrough fonts? Could you indicate me which function or class  I can refer to?

**Comment by HinTak** [comment]
These two seem to be part of SkPaint in skia which was removed 7 years ago https://github.com/mono/SkiaSharp/issues/391 . I checked there only one reference to these in current skia-python code, which is in the FontMetrics class. The Font class has a getMetrics method which gets it, but I don't think it supports setting. I.e. it looks like with current skia-python, you can try getting at the metrics of your current font of choice, then draw those lines at the returned positions... though I'd be happy to be corrected if you can set underlinewidth/strikeoutwidth to non-zero and get it to work that way.

In current upstream skia code, it seems that the skparagraph module has a text declaration class and a setter for this. So I'll open a new issue for binding skparagraph if one doesn't exist yet.

**Comment by HinTak** [comment]
There seems to be a custom typeface builder class which allows one to change the metrics of a supplied typeface.
https://github.com/google/skia/blob/b7ac9da3e5ac34baf5da70b3e37cdbfd898ed54b/include/utils/SkCustomTypeface.h#L34


Skia-python currently doesn't touch that, I think. Though it is designated SK_API, it is also not documented...

**Comment by haoxurt** [comment]
Thanks. I will close this issue.

**Comment by HinTak** [comment]
The custom typeface builder class seems stable (SK_API) so we might add that, besides the bigger skparagraph project.

**Comment by HinTak** [comment]
See the example in #258 on how to do underline / strikethrough. There is a donation link in from my profile https://hintak.github.io/ if you are feeling generous.

**Comment by HinTak** [comment]
You'll need to install the python wheels when CI finishes https://github.com/kyamagu/skia-python/actions/runs/10337416324 to try it out, of course.
