### ISSUE TITLE
deprecation of `distutils`upstream for python >= 3.12

### ISSUE THREAD

**Issue by HinTak** [kyamagu/skia-python#230]
Been getting this warning when I do local builds (`python setup.py ...`) for a while now:

```
skia-python/setup.py:8: DeprecationWarning: 

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 


  from numpy.distutils.ccompiler import CCompiler_compile
/usr/lib/python3.12/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
```

Nothing urgent yet, but possibly needs some work for python 3.13.

**Comment by HinTak** [comment]
Okay, that makes sense - I was wondering why it is `try: ... except: pass` doing nothing for not found. In that case it is just cosmetic, so I'd suggest adding a python version check to by-pass those few lines, to suppress the warning. I can add that at some point in time.

**Comment by kyamagu** [comment]
At this point, I would completely remove the `numpy.distutils` hack. [It seems pip supports parallel jobs as of now.](https://stackoverflow.com/questions/26669244/how-to-install-compile-pip-requirements-in-parallel-make-j-equivalent/57014278#57014278)

**Comment by HinTak** [comment]
I removed the numpy section and it looks fine, but there is actually a 2nd deprecatioin after that (it is in above, just overlooked):

```
/usr/lib/python3.12/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
```

**Comment by kyamagu** [comment]
@HinTak Can you try `python -m build --format wheel`? Directly calling `python setup.py build` is deprecated.

**Comment by HinTak** [comment]
Okay - I'll give it a try. Despite the deprecation warning about 3.12, it is still working on 3.12 at the moment...

**Comment by HinTak** [comment]
The first time I tried `python -m build --wheel` (it is `--wheel`, not `--format wheel`), I got "No such module build". Obviously I have never built python package that way before, despite about a decade of misc python usage :-).

It seems both of these deprecation messages came from `python setup.py ...` . Switching to `python -m build ...`, both of them disappeared. But it is a lot slower. The stackoverflow url you refers to says "Sometimes pip uses make to build dependencies" so defining MAKEFLAGS works. That's not the case here. Switching to `-m build ...` loses not only parallel build for me, but also seems to disable ccache (probably because of using virtualenv). So it is a lot slow for me for both fresh build and incremental build.

Since both came from `python setup.py ...`, I am okay to just close this (as it is my personal preference...) - I'll just continue this way as long as it works for me, ignore the warnings, until it does not. The parallel build setting could do better though. `-m build --wheel` is not using multi-CPUs. (Skia itself is - ninja auto-detect number of CPUs, o think).

**Comment by kyamagu** [comment]
Sure, you can ignore the warning for a moment

**Comment by lucach** [comment]
> Nothing urgent yet, but possibly needs some work for python 3.13.

Python 3.13 was officially released two days ago, so this is now a bit more urgent :)

A naive upgrade of the CI machinery indeed fails: https://github.com/lucach/skia-python/actions/runs/11382229349/job/31673721393

**Comment by HinTak** [comment]
Instead of trying to force 3.13 compat settings back to 3.8, might be easier to build 3.13 wheels separately /differently? (And gradually retiring the older python versions)

**Comment by HinTak** [comment]
I am trying something like this now: 
https://github.com/kyamagu/skia-python/pull/273
Supposedly just by-passing `try: ... except: pass` should work. @lucach I am wondering why you need to change the ubuntu versions etc? Are they necessary or just part of a routine updating everything? But you didn't update skia itself, and stayed at m126 :-). It is kind of difficult to tell which of your changes are already in m131 - we did have to update manylinux a few months ago, out of necessity. Some of the other updates are out of ci node deprecation warnings. I would just to to be clear which changes are necessary and which changes are "nice to keep up in general".

**Comment by lucach** [comment]
> @lucach I am wondering why you need to change the ubuntu versions etc? Are they necessary or just part of a routine updating everything?

Oh, there is no deep motivation behind any of those changes: I just wanted to try to naively upgrade what seemed reasonable. Feel free to ignore all of them, unless necessary.

I don't have any particular insight to share, except that [GitHub now offers Apple M1 runners (i.e., arm64)](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) which would probably significantly speed up the build for that platform which is now emulated. However, this is a separate issue from supporting 3.13.

**Comment by HinTak** [comment]
The apple runner issue is a bit more complicated - x86_64 is emulated... I.e. gitbub offers only one arch under the free plan, and it switches between macos13 and 14, I think.

**Comment by HinTak** [comment]
I don't quite understand - it seems to be failing for 3.8 / 3.9 (only) on Linux, just removing those lines. And making things conditional on python version did not work - it seems the 3.8/3.9 wheels are built with python 3.12 against bits from older versions, instead of genuinely with old python. Seems to require splitting linux into 3.8/3.9 vs later, somehow, to make this thing work.

**Comment by HinTak** [comment]
Surely there should be other people experiencing the same problem with other packages.

**Comment by HinTak** [comment]
Yes, we could drop 3.8 in the 3.13 update, but 3.9 is actually still one year from EOL. That probably explains the 3.8/3.9 failure - might have to lock numpy version to last to make it work.

**Comment by HinTak** [comment]
It looks as if the numpy version is already locked to older version for 3.8.

**Comment by HinTak** [comment]
@kyamagu @lucach sorry for the mess in #273 . It looks like for most parts it is not even about skia-python itself, but github's cibuildwheel action - you need an old version - and its bundled virtual build environment to build 3.8/3.9 (and it doesn't support 3.13), but a new version to build 3.13 (and that drops 3.8/3.9). So that leaves us a little problem of having to split the buildwheel step into two . and waste some cpu time, since each of them build skia at the beginning; so we end up build skia 3 or 4 times more than we need to. (For each arch/platform, splitting into 3.8/3.9 vs 3.10-3.13). This important thing is really that 3.9 is not EOL for another year, so numpy probably shouldn't.

Actually I wonder if it is merely 3.8 that breaks - we can legitimately ask for 3.9 to work in cibuildwheel for another year.

**Comment by HinTak** [comment]
numpy distutils isn't needed, but it seems that cibuildwheel itself is being a bit inconsistent, and use one version of python to populate the venv environment and another to build.

**Comment by HinTak** [comment]
Okay, splitting and duplicating the cibuildwheel section into new/old works. It is a bit messy, both the process of doing it (I intend to withdraw / force-push #273 to clean up the history), and the outcome, having two nearly identical build_wheel sections, and the fact that we waste CPU cycles building upstream skia a few times more than needed.

**Comment by HinTak** [comment]
Just looking for something else and saw this: https://github.com/actions/runner-images/issues/10812 3.9 and also 3.10 being removed from mac os runners next month!
