### ISSUE TITLE
Is there a way to use skia.Surface to export high quality images?

### ISSUE THREAD

**Issue by adelhpour** [kyamagu/skia-python#233]
I am trying to draw a figure on the canvas using skin.Surface. It works perfect, but the only thing I could not figure out is that when I use surface.makeImageSnapshot() method and then save the image, as it is described in the documentation, I am getting a image which is not of high quality and is small in its size. I was wondering if there is a way I can set the quality/resolution of the exported image?

**Comment by HinTak** [comment]
I think you generally get an image which is the same pixel size as the declared dimension of the surface. So one answer to your question is probably just drawing on a larger surface. One other possibility is the `SamplingOptions` class, which is a translation of the upstream `SkSamplingOptions` class. This is used as an argument to many image-related methods. In skia-python we only provides the default at the moment, but it won't surprise me that upstream has a resolution-doubling etc option. If you look at the upstream documentation and see if you can find what you need there, we can put it in the next (122)  release. A 3rd possibility is to output as one of the vector formats (svg, ps, pdf etc) and rasterize externally with mupdf/batik/ghostscript. For that, you need to worry about pen width, etc.

**Comment by HinTak** [comment]
The SamplingOptions class seems to have a number of enums, `kLinear` and `kNearest` for interpolation. I don't know which might be relevant to you (or none), but if you are trying to draw a bitmap onto a surface that is not exactly the same pixel dimension as the bitmap, you might find changing from kLinear to KNearest or vice versa more suited to your needs.

**Comment by adelhpour** [comment]
Thanks for your quick reply.
What I am actually looking for is that how I can use the following methods mentioned in the documentation:

**Comment by HinTak** [comment]
Well, I wrote everything in my initial reply already: easiest would be starting from a larger surface. 2nd way is to use `image.resize()`, which takes a `SamplingOption` argument for interpolation. If the current python interface to the upstream `SkSamplingOption` class is insufficient and you see things upstream we could add, we'll add it for next release. Upstream docs at api.skia.org or something similar.

**Comment by HinTak** [comment]
https://api.skia.org/structSkSamplingOptions.html
