### ISSUE TITLE
Missing `getBlendMode` on `skia.Paint` objects

### ISSUE THREAD

**Issue by pavpanchekha** [kyamagu/skia-python#235]
There is a `setBlendMode` method on `Paint` objects, but no corresponding `getBlendMode`. Also, the `BlendMode` parameter to `skia.Paint` is not documented

**To Reproduce**
```
>>> skia.__version__
'119.0b4'
>>> skia.Paint().getBlendMode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'skia.Paint' object has no attribute 'getBlendMode'. Did you mean: 'setBlendMode'?
```
To see the documentation issues, search "blendmode" on this page: https://kyamagu.github.io/skia-python/reference/skia.Paint.html
Note that the `BlendMode` argument to the `skia.Paint` constructor works, but is not documented.

**Expected behavior**
Like in previous releases of `skia-python`, the `getBlendMode` function should exist and be documented.

**Desktop:**
 - OS: macOS 14.3.1
 - Python: 3.12
 - skia-python version: 119.0b4

**Comment by HinTak** [comment]
`getBlendMode` was removed upstream. There is a new `getBlendMode_or(...)` function, which seems to overlap somewhat in functionality. Patch welcome.

**Comment by HinTak** [comment]
This was removed in https://github.com/google/skia/commit/64e67c346c3fe386cda542386831f65d39098bda, which also provides the code for emulating it.

**Comment by HinTak** [comment]
BlendMode is a class itself - that should be obvious? You read the BlendMode class documentation on what it means.

**Comment by HinTak** [comment]
I have put the emulation in https://github.com/kyamagu/skia-python/pull/234/commits/69e25c32dc54f120be6228432d06c1b4cf037b2e . Download the new build when it finishes to give it a try if you can.

I am not going to release that as 123bX as 124 is already out, so there will be a pull for m124-public soon, and 124bX will ship with this fix.

**Comment by pavpanchekha** [comment]
Thank you, perfect. I'll check it out later today. By `BlendMode` documentation, I mean that `BlendMode` isn't in the list of possible keyword arguments for `skia.Paint.__init__`, even though it in fact appears to be a valid keyword argument.

**Comment by HinTak** [comment]
The docstring indeed seems to never mention Blendmode despite the code clearly can accept it. How do you list the possible keyword arguments?

**Comment by pavpanchekha** [comment]
Ok, confirming that that build worked. Thank you!
