### ISSUE TITLE
Identify what breaks in m122 for font(typeface("")) on mac os

### ISSUE THREAD

**Issue by HinTak** [kyamagu/skia-python#241]
It is somewhat expected given the other changes, but it would be nice to identify the precise upstream commit/diff that causes font(typeface('')) to stop working in mac os x in m122.
See https://github.com/kyamagu/skia-python/pull/232#issuecomment-1924104619 .

font(typeface('times')) should work everywhere?

**Comment by HinTak** [comment]
Times also gives `glyphs_Times = [0, 0, 0, 0, 0]`

**Comment by pavpanchekha** [comment]
I just ran into this locally. Even passing an explicit font seems to break:

```
>>> import skia
>>> skia.Typeface("Arial")
Typeface('', FontStyle(400, 5, Slant.kUpright_Slant))
```

The expected result (`Typeface('Arial', FontStyle(400, 5, Slant.kUpright_Slant)`) occurs on 121.0b6

**Comment by HinTak** [comment]
Yes, I tried "Times" on CI and it doesn't work either.
https://github.com/kyamagu/skia-python/compare/3cf8711bdf2309325cf40f1a65ee8c59707f9a0b..ead48c542529c6c7f5d96692e3c27c3c718b929d

**Comment by pavpanchekha** [comment]
I found the issue: https://github.com/HinTak/skia-python/pull/1

Not sure I made the PR on the right repo, sorry @HinTak!

**Comment by HinTak** [comment]
@pavpanchekha doesn't matter which repo - I can cherry-pick it across.

**Comment by HinTak** [comment]
I have cherry-picked across to all of them now.
