### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by Well2333** [kyamagu/skia-python#242]
I've noticed that Python 3.12 has been officially released for a while, but skia-python still does not support this version. I noticed that there was an attempt to address this issue in issue #206, and a related pull request was also submitted. However, the issue marked as  resolved BUT the pull request was closed without merging, leading the problem still exist till now.

Is there any plan to add support for Python 3.12 in the near future? Many users including myself would greatly benefit from this update due to the new features and improvements in Python 3.12.

**Comment by HinTak** [comment]
It was already done : https://github.com/kyamagu/skia-python/pull/203

We are not going to put more v87.x out - try v1xx beta's.

**Comment by HinTak** [comment]
121b6 is current - https://pypi.org/project/skia-python/121.0b6/ . 124b7 is probably going to be out soon, when #236 is merged.
