### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by jonathanhogg** [kyamagu/skia-python#276]
Hiya!

I hate to be a pain, but is there any news on when there might be either a new beta with wheels for Python 3.13 or the addition of 3.13 wheels to the 130.0b10 packages on PyPI?

I had a go at building HEAD myself with Python 3.13 and it seems to work fine and pass my own tests.

**skia-python** is the last of my dependencies without 3.13 support.

**Comment by HinTak** [comment]
Don't worry, it isn't a pain - we have been talking about 3.13 support in a different thread (#230). There was an early attempt at 3.13 (#273) ; it worked in the end but was a mess, so I closed it and put out a tidied version (#275) You haven't looked under the pull here? There is a 131 pull, and a 131 + py 3.13 pull. You should be able to download a pre-built wheel from the action tab. https://github.com/kyamagu/skia-python/actions/runs/11515703561

Since I already tidied it up, Backporting the change is minimal work - do you want to give the m131 +py3.13 wheel a try, or do you insist oh a m130 + py3.13 wheel?

**Comment by HinTak** [comment]
@jonathanhogg okay, I made v130+py3.13 pull anyway, and you should be able to download a prebuilt wheel from ci https://github.com/kyamagu/skia-python/actions/runs/11520549675 in about 5 hours, when the build finishes. Though I would prefer you to give m131+py3.13 build wheels a go. As usual, if you use skia-python for work, please consider clicking the donate/sponsor button under my profile.

**Comment by HinTak** [comment]
From your other repos, it looks like you might be interested in runtime shader effects - https://github.com/kyamagu/skia-python/pull/274 - would you be interested in having that together too? 

The m130 to m131 itself is very simple / straightforward, but the "m131 + py3.13" and "m131 + runtime effects" are kept separate.

**Comment by jonathanhogg** [comment]
Oh, I'm not particularly wedded to v130 – I tend to always track the latest beta anyway.

Hmmm… I've not got a lot of time to look at the SkShader stuff at the moment, but it does sound interesting.

At the moment it's more that `skia-python` is a dependency for my package `flitter-lang`, so I don't want to release 3.13 packages for that until one can actually install it…

**Comment by HinTak** [comment]
@jonathanhogg if you mean doing `pip install --pre ...`, then unless we discover major problems in the next few weeks with #275, it will be merged with #274 (and its later updates) in about 3 weeks , depending on how much m132 differs from m131, we release m131b11 or m132b11. So the most you need to wait for python 3.13 wheels from `pip install --pre ...` is about 3 weeks.

If you mean just for yourself to try out, you can do it now from the actions tabs. I think the 3.13-related changes don't need any more work. We'd appreciate some testing.

The runtime effect addition looks very interesting - although I only managed to port 4 of the 9 "official" c++ example to skia-python so far, it already covers the simpler use-cases. I'll have some figures in the accompanying example repo, you can have a look at both the example code and the generated output to see what you think, and I hope it gets your interest.
