### ISSUE TITLE
Wayland doesn't seem to work.

### ISSUE THREAD

**Issue by Sectonidse** [kyamagu/skia-python#280]
**Describe the bug**
Every time i create a GL context on Wayland, it fails, while on X11 it works just fine.

**To Reproduce**
1. Use Wayland desktop manager
2. Run a Python script that creates a GLFW window and Skia's GL context.
3. Get the `AttributeError: 'NoneType' object has no attribute 'getCanvas'`

**Expected behavior**
Working fine just as in X11.

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu 24.10
 - Python: 3.12
 - skia-python version: v130.0b10

**Additional context**
I'm not really sure where to post about this so i chose to do it over here. I did the research about this and repeated multiple times just in case if i missed anything, but found nothing about the current status of Wayland support of the Skia itself. I've been trying to deal with this issue for more than a month; there's no way for me to create an XWayland window or create other workarounds.

**Comment by HinTak** [comment]
Known problem - see https://github.com/HinTak/skia-python-examples

**Comment by HinTak** [comment]
On Wayland-based platforms (i.e. very new Linux systems), setting SDL_VIDEODRIVER=x11 may be needed for the SDL example; the equivalent for the GLUT example is PYOPENGL_PLATFORM=glx . If you use other methods of creating a gl context, google for it - it is usually about needing to set an environment variable. GLFW works transparently on wayland, nothing else needed.

**Comment by HinTak** [comment]
If you are using glfw and having problems, you may have an old glfw - see https://github.com/glfw/glfw/issues/2558

**Comment by HinTak** [comment]
The 3 `issue-214-`* examples in https://github.com/HinTak/skia-python-examples all ran under wayland. For two of them, sdl2 and pyopengl, setting env was needed. The glfw example did not need anything else. The repo was basically created when I was investigating sdl2 wayland problems in #214.

**Comment by Sectonidse** [comment]
Hi! Thanks for the reply. I've been trying to make this work, but still can't do it. I tried to run `issue-214-glfw.py` and it failed on Wayland. Here's how output looks like:
```python
<CDLL '/usr/lib/x86_64-linux-gnu/libglfw.so.3.4', handle af09800 at 0x7a8e9c1c1550>
b'NVIDIA Corporation'
b'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
b'3.2.0 NVIDIA 560.35.03'
b'1.50 NVIDIA via Cg compiler'
Traceback (most recent call last):
  File [...], line 50, in <module>
    assert context is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```
I even set up the env variable `PYOPENGL_PLATFORM=glx` but it still did not work...

Additional info:
OS: Kubuntu 24.10 (same happens on Ubuntu 24.04, Ubuntu 24.10, and Debian)
Kernel: 6.11.0-9-generic (64-bit)
KDE Plasma: 6.1.5
NVIDIA GPU might not be at fault here, because my Ubuntu 24.10 laptop without any GPU also cannot run this.

**Comment by HinTak** [comment]
I assume you are using the proprietary nvidia driver on Linux, rather than the open-source one? You may need to switch to the open-source driver to get some special functionality - and vice versa - some graphics capabilities works better with the open-source driver, some better with the proprietary one. I just have vanilla Intel graphics chip on my laptop, so it is just open-source and mesa. All three samples work under wayland 6 months ago, with the 2 workarounds for the 3 examples. I have personally switched to boot x11 by default because I intend to look at the sdl issue a bit more (there are some mouse co-ordinate issue - it is filed under that repo). But as far as I know, glfw (a recent one) works with wayland.

**Comment by HinTak** [comment]
It might be a ubuntu problem - try building libglfw (or download a prebuilt binary) yourself. The instruction to load your own libglfw is somewhere linked from #214 on the pyglfw repo.

**Comment by HinTak** [comment]
I log out of x11 and re-login to wayland (on fedora it is just a log-in option). The only one that needs a work around is the sdl2 one. The glut one does not need it. (The readme had it just for completeness/ slightly older pyopengl,  I think).

**Comment by HinTak** [comment]
I think it is most likely that ubuntu ships glfw without wayland support compiled in.

Can you try the tip in https://github.com/FlorianRhiem/pyGLFW/issues/80#issuecomment-2134783612 , setting
`PYGLFW_LIBRARY` to your own copy of libglfw and make sure that you compile it with wayland support on? I have 3.3.10 on fedora.

Or use the nouveau open-source driver (if that works with your hardware).
