### ISSUE TITLE
How to use on GPU headless backend

### ISSUE THREAD

**Issue by Swarzox** [kyamagu/skia-python#286]
Hello, I'm trying to use Skia Python on a GPU-enabled headless backend server. Is there a way to achieve this? I haven't been able to make it work.

**Comment by HinTak** [comment]
It is at the beginning of the tutorial, and specifically  our CI tests are run in a headless environment. This line https://github.com/kyamagu/skia-python/blob/db7d7fcc84dc5e59ea8a925457f2d319a57052df/tests/conftest.py#L16

**Comment by HinTak** [comment]
Specifically this section https://kyamagu.github.io/skia-python/tutorial/canvas.html#gpu

**Comment by Swarzox** [comment]
Hello @HinTak I always have this error :
`/opt/conda/lib/python3.10/site-packages/glfw/__init__.py:917: GLFWError: (65550) b'X11: The DISPLAY environment variable is missing'`

I tried with xvfb and it worked however I can't get GPU acceleration with this

**Comment by HinTak** [comment]
This topic is outside skia-python, really. You need to search for "accelerated X11 headless" or "accelerated GPU headless", and read articles like:
https://stackoverflow.com/questions/7448597/how-can-i-take-advantage-of-my-discrete-graphics-card-on-a-headless-server

We can't help you further on this.
