### ISSUE TITLE
Add examples of interaction with Pillow & Wand & fs

### ISSUE THREAD

**Issue by cdplayer** [kyamagu/skia-python#40]
**Is your feature request related to a problem? Please describe.**
I'm a beginner at Python and have been looking as Skia recently and wanted to use some of it's unique features. This is the first(only?) python library that seems to be complete that i found. Could you please add some examples of interaction or exchange of information with Pillow and Wand. And also saving or reading from files. ie eliminate use of ipython calls.

**Describe the solution you'd like**
Examples
- Read from file.
- Add skia content.
- Do Pillow / Wand content to 'canvas'
- Add skia content.
- Save to a file(skia)

**Describe alternatives you've considered**
Could not get the Ipython package working on my system so was a bit lost of how to use skia-python. it does appear to work but can't show or display or save to file.

**Comment by kyamagu** [comment]
Thanks for your request. Right now the package is under active development and lacks tutorial documentation. For now, you can get an idea of how to export an image to fs:

```python
surface = skia.Surface(256, 256)
canvas = surface.getCanvas()
# Do whatever with the canvas
image = surface.makeImageSnapshot()
with open('output.png') as f:
    f.write(image.encodeToData())
```

**Comment by kyamagu** [comment]
Also check the [Overview](https://github.com/kyamagu/skia-python/blob/master/notebooks/Canvas-Overview.ipynb) notebook

**Comment by kyamagu** [comment]
[Python Image I/O notebook](https://github.com/kyamagu/skia-python/blob/master/notebooks/Python-Image-IO.ipynb) is available.
