### ISSUE TITLE
NumPy array with incorrect dtype silently proceeds

### ISSUE THREAD

**Issue by kyamagu** [kyamagu/skia-python#67]
**Describe the bug**
NumPy array conversion to, e.g., `Image` silently accepts array with types other than uint8.

**To Reproduce**
```
import skia
import numpy as np

array = np.zeros((100, 100), dtype=np.float32)
image = skia.Image(array)
```

**Expected behavior**
Should throw an error.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Architecture x86_64
 - Python 3.7
 - skia-python version v0.0.4

**Additional context**
n/a

**Comment by kyamagu** [comment]
Resolved by #70

**Comment by Correct-Syntax** [comment]
Hi @kyamagu , is this to say that only ``uint8`` image are supported?

**Comment by kyamagu** [comment]
@Correct-Syntax [See the available color types in the documentation.](https://kyamagu.github.io/skia-python/reference/skia.ColorType.html#skia.ColorType)

**Comment by Correct-Syntax** [comment]
@kyamagu thank you.
