### ISSUE TITLE
Add proper bindings for when SK_SUPPORT_GPU is enabled

### ISSUE THREAD

**Issue by NextLight** [kyamagu/skia-python#85]
**Is your feature request related to a problem? Please describe.**
I would like to use skia with glfw (to display realtime graphics, similar to [here](https://gist.github.com/ad8e/dd150b775ae6aa4d5cf1a092e4713add)).  
The issue is that the current bindings don't expose the correct GrBackendRenderTarget constructors since they are under an `#if SK_SUPPORT_GPU`, as it can be seen in the [.h file](https://api.skia.org/GrBackendSurface_8h_source.html).

**Describe the solution you'd like**
I guess you are generating the bindings in some automated way, so it should be as simple as setting SK_SUPPORT_GPU to true when generating them.

**Describe alternatives you've considered**
I wasn't able to use the GPU example you provided in the docs to to that, it can only generate an image.

**Comment by kyamagu** [comment]
For now, use `Surface.MakeRenderTarget`
